import type { BashReadonlyCommandPolicy } from "./bash-readonly-policy-types.js";
import {
  dateCommandIsDangerous,
  jqCommandIsDangerous,
  lsofCommandIsDangerous,
  manCommandIsDangerous,
  psCommandIsDangerous,
  pyrightCommandIsDangerous,
  sedCommandIsDangerous,
  ssCommandIsDangerous,
  testCommandIsDangerous,
  tputCommandIsDangerous,
  xargsCommandIsDangerous,
} from "./bash-readonly-policy-callbacks.js";
import {
  BASE64_SAFE_FLAGS,
  CAT_SAFE_FLAGS,
  DATE_SAFE_FLAGS,
  FD_SAFE_FLAGS,
  FILE_SAFE_FLAGS,
  GREP_SAFE_FLAGS,
  HEAD_TAIL_SAFE_FLAGS,
  HOSTNAME_SAFE_FLAGS,
  JQ_SAFE_FLAGS,
  LSOF_SAFE_FLAGS,
  MAN_SAFE_FLAGS,
  NETSTAT_SAFE_FLAGS,
  PGREP_SAFE_FLAGS,
  PS_SAFE_FLAGS,
  PYRIGHT_SAFE_FLAGS,
  RG_SAFE_FLAGS,
  SED_SAFE_FLAGS,
  SHA_SUM_SAFE_FLAGS,
  SORT_SAFE_FLAGS,
  SS_SAFE_FLAGS,
  TEST_SAFE_FLAGS,
  TPUT_SAFE_FLAGS,
  TREE_SAFE_FLAGS,
  WC_SAFE_FLAGS,
  XARGS_SAFE_FLAGS,
} from "./bash-readonly-policy-flags.js";

// git 全局参数分类。安全集只收「不改 git 行为语义」的参数：它们不注入配置、不换 gitdir 或
// 工作树、不执行外部子命令，因此剥掉之后子命令的 safeFlags 判定仍然成立。
// 反过来，带值参数一律不靠「前缀无害」放行——值本身可能改变行为，逐类给出依据后才进安全集。
export const GIT_GLOBAL_NO_VALUE_FLAGS = new Set(["--no-pager", "--paginate"]);
// -C 只切换相对路径与仓库发现的起点目录，不注入配置也不换 gitdir/work-tree；
// 但它会改变 git 加载 .git/config/hooks 的目录，所以消费它的同时必须校验目标目录
// （见 bash-readonly-policy-argv-git.ts 的 gitChangeDirectoryArgumentIsSafe）。
// 目前只允许 -C：新增带值成员时必须同时在 normalizeGitArgv 里分派对应的校验函数，
// 不能默认套用 -C 的目录语义。
export const GIT_GLOBAL_VALUE_FLAGS = new Set(["-C"]);
export const GIT_GLOBAL_DANGEROUS_FLAGS = new Set([
  "-c",
  "--attr-source",
  "--bare",
  "--config-env",
  "--exec-path",
  "--git-dir",
  "--namespace",
  "--shallow-file",
  "--super-prefix",
  "--work-tree",
]);

export const READONLY_COMMAND_POLICIES = new Map<string, BashReadonlyCommandPolicy>([
  ["alias", { commandOnly: true }],
  ["base64", { safeFlags: BASE64_SAFE_FLAGS, respectsDoubleDash: false }],
  ["cat", { safeFlags: CAT_SAFE_FLAGS }],
  ["cd", { allowAnyArgs: true }],
  ["cut", { allowAnyArgs: true }],
  [
    "date",
    { safeFlags: DATE_SAFE_FLAGS, additionalCommandIsDangerousCallback: dateCommandIsDangerous },
  ],
  ["diff", { allowAnyArgs: true }],
  ["dirname", { allowAnyArgs: true }],
  ["du", { allowAnyArgs: true }],
  ["echo", { allowAnyArgs: true }],
  ["egrep", { safeFlags: GREP_SAFE_FLAGS }],
  ["false", { commandOnly: true }],
  ["fd", { safeFlags: FD_SAFE_FLAGS }],
  ["file", { safeFlags: FILE_SAFE_FLAGS }],
  ["find", { allowAnyArgs: true }],
  ["fgrep", { safeFlags: GREP_SAFE_FLAGS }],
  ["fdfind", { safeFlags: FD_SAFE_FLAGS }],
  ["grep", { safeFlags: GREP_SAFE_FLAGS }],
  ["head", { safeFlags: HEAD_TAIL_SAFE_FLAGS }],
  ["help", { safeFlags: { "-d": "none", "-m": "none", "-s": "none" } }],
  ["hexdump", { allowAnyArgs: true }],
  [
    "hostname",
    { safeFlags: HOSTNAME_SAFE_FLAGS, regex: /^hostname(?:\s+(?:-[a-zA-Z]|--[a-zA-Z-]+))*\s*$/ },
  ],
  ["id", { allowAnyArgs: true }],
  ["jq", { safeFlags: JQ_SAFE_FLAGS, additionalCommandIsDangerousCallback: jqCommandIsDangerous }],
  [
    "lsof",
    { safeFlags: LSOF_SAFE_FLAGS, additionalCommandIsDangerousCallback: lsofCommandIsDangerous },
  ],
  ["ls", { allowAnyArgs: true }],
  [
    "man",
    { safeFlags: MAN_SAFE_FLAGS, additionalCommandIsDangerousCallback: manCommandIsDangerous },
  ],
  ["md5sum", { safeFlags: SHA_SUM_SAFE_FLAGS }],
  ["netstat", { safeFlags: NETSTAT_SAFE_FLAGS }],
  ["nl", { allowAnyArgs: true }],
  ["pgrep", { safeFlags: PGREP_SAFE_FLAGS }],
  ["ps", { safeFlags: PS_SAFE_FLAGS, additionalCommandIsDangerousCallback: psCommandIsDangerous }],
  [
    "pyright",
    {
      safeFlags: PYRIGHT_SAFE_FLAGS,
      respectsDoubleDash: false,
      additionalCommandIsDangerousCallback: pyrightCommandIsDangerous,
    },
  ],
  ["printf", { allowAnyArgs: true }],
  ["pwd", { commandOnly: true }],
  ["readlink", { allowAnyArgs: true }],
  ["realpath", { allowAnyArgs: true }],
  ["rev", { allowAnyArgs: true }],
  ["rg", { safeFlags: RG_SAFE_FLAGS }],
  [
    "sed",
    { safeFlags: SED_SAFE_FLAGS, additionalCommandIsDangerousCallback: sedCommandIsDangerous },
  ],
  ["sha1sum", { safeFlags: SHA_SUM_SAFE_FLAGS }],
  ["sha256sum", { safeFlags: SHA_SUM_SAFE_FLAGS }],
  ["sort", { safeFlags: SORT_SAFE_FLAGS }],
  ["ss", { safeFlags: SS_SAFE_FLAGS, additionalCommandIsDangerousCallback: ssCommandIsDangerous }],
  ["stat", { allowAnyArgs: true }],
  ["strings", { allowAnyArgs: true }],
  ["tail", { safeFlags: HEAD_TAIL_SAFE_FLAGS }],
  [
    "test",
    {
      safeFlags: TEST_SAFE_FLAGS,
      respectsDoubleDash: false,
      additionalCommandIsDangerousCallback: testCommandIsDangerous,
    },
  ],
  [
    "tput",
    { safeFlags: TPUT_SAFE_FLAGS, additionalCommandIsDangerousCallback: tputCommandIsDangerous },
  ],
  ["tr", { allowAnyArgs: true }],
  ["tree", { safeFlags: TREE_SAFE_FLAGS }],
  ["true", { commandOnly: true }],
  ["uniq", { allowAnyArgs: true }],
  ["uname", { allowAnyArgs: true }],
  ["wc", { safeFlags: WC_SAFE_FLAGS }],
  ["which", { allowAnyArgs: true }],
  ["whoami", { commandOnly: true }],
  [
    "xargs",
    { safeFlags: XARGS_SAFE_FLAGS, additionalCommandIsDangerousCallback: xargsCommandIsDangerous },
  ],
  [
    "[",
    {
      safeFlags: TEST_SAFE_FLAGS,
      respectsDoubleDash: false,
      additionalCommandIsDangerousCallback: testCommandIsDangerous,
    },
  ],
  [
    "[[",
    {
      safeFlags: TEST_SAFE_FLAGS,
      respectsDoubleDash: false,
      additionalCommandIsDangerousCallback: testCommandIsDangerous,
    },
  ],
]);

export const READONLY_ALLOW_ANY_ARG_COMMANDS = new Set([
  "basename",
  "cal",
  "cat",
  "cmp",
  "column",
  "comm",
  "cut",
  "df",
  "diff",
  "dirname",
  "du",
  "expand",
  "expr",
  "false",
  "fmt",
  "fold",
  "free",
  "groups",
  "head",
  "hexdump",
  "id",
  "locale",
  "nl",
  "nproc",
  "numfmt",
  "od",
  "paste",
  "pr",
  "readlink",
  "realpath",
  "rev",
  "seq",
  "sleep",
  "stat",
  "strings",
  "tac",
  "tail",
  "tr",
  "true",
  "tsort",
  "type",
  "uname",
  "unexpand",
  "uptime",
  "wc",
  "which",
]);

export const READONLY_ALLOW_ANY_ARG_COMMAND_PREFIXES = [
  ["docker", "images"],
  ["docker", "ps"],
] as const;
